# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_valid',
        ),
    ]
